export type ValidSkills =
  | "Python"
  | "TensorFlow"
  | "PyTorch"
  | "Keras"
  | "Scikit-learn"
  | "SQL"
  | "Natural Language Processing"
  | "Computer Vision"
  | "Big Data"
  | "Data Engineering"
  | "Predictive Modeling"
  | "Model Optimization"
  | "Data Analysis"
  | "Data Visualization"
  | "TypeScript"
  | "Java"
  | "HTML"
  | "CSS"
  | "Amazon Web Services"
  | "Spring Security"
  | "Spring Boot"
  | "Angular"
  | "MinIO"
  | "MySQL"
  | "MongoDB"
  | "Git"
  | "Docker"
  | "GitHub"
  | "Docker"
  | "Amazon S3"
  | "Amazon Web Services"
  | "Amazon EC2"
  | "Amazon DocumentDB"
  | "Amazon RDS"
  | "Amazon Route 53"
  | "Amazon VPC"
  | "Amazon Certificate Manager"


export type ValidCategory =
  | "Machine Learning"
  | "Data Science"
  | "Data Engineering"
  | "Cloud Computing"
  | "Predictive Maintenance"
  | "Deep Learning"
  | "Software Engineering"
  | "Web Development"
  | "Frontend Development"
  | "Backend Development"
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling"
  | "Freelance"
  | "Anomaly Detection"
  | "Amazon Web Services"

export type ValidExpType = "Personal Project" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "experience"
  | "contact"
  | "projects"
  | "resume";
