export const siteConfig = {
  name: "Jesús Martín Trilla Portfolio",
  authorName: "Jesús Martín Trilla",
  username: "Jemartri44",
  description:
    "Jesús Martín Trilla is a Full Stack Developer, who loves to build web applications and is passionate about learning new technologies.",
  url: "https://jesusmartintrilla.dev",
  links: {
    github: "https://github.com/jemartri44",
  },
  ogImage: "https://jesusmartintrilla.dev/1743651219647.jpg",
  keywords: [
    "Jesús Martín Trilla",
    "jesusmartintrilla",
    "jesusmartintrilla.dev",
    "Martín Trilla",
    "Junior Machine Learning Engineer",
    "Machine Learning",
    "Machine Learning Engineer",
    "Aprendizaje Automático",
    "Ingeniero de Aprendizaje Automático",
    "Artificial Intelligence",
    "Inteligenia Artificial",
    "Data Science",
    "Data Scientist",
    "Data Engineer",
    "Data Engineering",
    "Data Analysis",
    "Ciencia de Datos",
    "Ingeniería de Datos",
    "Ingeniero de Datos",
    "Deep Learning",
    "Neural Networks",
    "Deep Learning Engineer",
    "Deep Neural Networks",
    "NLP",
    "Natural Language Processing",
    "Aprendizaje Profundo",
    "Redes Neuronales",
    "Ingeniero de Aprendizaje Profundo",
    "Python",
    "TensorFlow",
    "PyTorch",
    "Ingeniero Junior de Aprendizaje Automático",
    "Aprendizaje Automático",
    "Inteligencia Artificial",
    "Ciencia de Datos",
    "Aprendizaje Profundo",
    "Natural Language Processing",
    "Procesamiento de Lenguaje Natural",
    "NLP",
    "Computer Vision",
    "Big Data",
    "Keras",
    "Scikit-learn",
    "SQL",
    "Ingeniería de Datos",
    "Modelado Predictivo",
    "Optimización de Modelos",
    "Análisis de Datos",
    "Programación en Python",
    "Desarrollo de Algoritmos",
    "Visualización de Datos",
    "Cloud",
    "Cloud Computing",
    "AWS",
    "Google Cloud Platform",
    "Habilidades Analíticas",
    "Resolución de Problemas",
    "Trabajo en Equipo",
    "Aprendizaje Continuo",
    "Informático",
    "Ingeniero de Software",
    "Ingeniero informático",
    "Ingeniero de Datos",
    "Ingeniero junior",
    "Ingeniero de Aprendizaje Automático",
    "Ingeniero de Aprendizaje Automático Junior",
    "Ingeniero de Aprendizaje Automático Junior",
    "Desarrollador Junior",
    "Desarrollador de Software",
    "Angular",
    "TypeScript",
    "JavaScript",
    "Web Development",
    "Frontend Development",
    "HTML",
    "CSS",
    "Responsive Design",
    "Single Page Applications",
    "SPA",
    "Angular Material",
    "Web Components",
  ],
};
