export const siteConfig = {
  name: "Jesús Martín Trilla Portfolio",
  authorName: "Jesús Martín Trilla",
  username: "jemartri44",
  description:
    "Jesús Martín Trilla is a Full Stack Developer, who loves to build web applications and is passionate about learning new technologies.",
  url: "https://jesusmartintrilla.dev",
  links: {
    github: "https://github.com/jemartri44",
  },
  ogImage: "https://jesusmartintrilla.dev/1743651219647.jpg",
  keywords: [
    "Jesús Martín Trilla",
    "Junior Machine Learning Engineer",
    "Machine Learning",
    "Artificial Intelligence",
    "Data Science",
    "Deep Learning",
    "Python",
    "TensorFlow",
    "PyTorch",
    "Ingeniero Junior de Aprendizaje Automático",
    "Aprendizaje Automático",
    "Inteligencia Artificial",
    "Ciencia de Datos",
    "Aprendizaje Profundo",
    "Natural Language Processing",
    "Procesamiento de Lenguaje Natural",
    "NLP",
    "Computer Vision",
    "Big Data",
    "Keras",
    "Scikit-learn",
    "SQL",
    "Ingeniería de Datos",
    "Modelado Predictivo",
    "Optimización de Modelos",
    "Análisis de Datos",
    "Programación en Python",
    "Desarrollo de Algoritmos",
    "Visualización de Datos",
    "Cloud",
    "Cloud Computing",
    "AWS",
    "Google Cloud Platform",
    "Habilidades Analíticas",
    "Resolución de Problemas",
    "Trabajo en Equipo",
    "Aprendizaje Continuo",
    "Informático",
    "Ingeniero de Software",
    "Ingeniero informático",
    "Desarrollador de Software",
    "Angular",
    "TypeScript",
    "JavaScript",
    "Web Development",
    "Frontend Development",
    "HTML",
    "CSS",
    "Responsive Design",
    "Single Page Applications",
    "SPA",
    "Angular Material",
    "Web Components",
  ],
};
